name: Build and Push Docker Image

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Log in to GitHub Container Registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/docker-ci-cd:latest .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/docker-ci-cd:latest
